# Generated by Django 5.0.6 on 2024-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_membership'),
        ),
    ]
